[package]
name = "cao-q-client"
version = "0.1.0"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cao-queue = { path = "../cao-queue", no-default-features = true, features = [
    "serde"
] }
servo-websocket = "0.21"
reqwest = "*"
url = "2"
