apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: caoq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caoq
  serviceName: caoq
  template:
    metadata:
      labels:
        app: caoq
    spec:
      containers:
        - name: caoq
          imagePullPolicy: Always
          image: frenetiq/caoq:bleeding
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "6942"
          livenessProbe:
            httpGet:
              path: /health
              port: 6942
            initialDelaySeconds: 1
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: caoq
spec:
  type: LoadBalancer
  ports:
    - name: caoq
      port: 6942
  selector:
    app: caoq
